packages:
  base: !include packages/base.yml
  device_base: !include boards/m5stack-nanoc6.yml

dashboard_import:
  package_import_url: github://yoziru/esphome-m5-btproxy/btproxy-m5stack-nanoc6-i2c.yml

# Illuminance Sensor
i2c:
  - id: grove
    sda: 2
    scl: 1
    scan: true

sensor:
  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 5s
