substitutions:
  friendly_name: M5 BTProxy
  device_name: m5-btproxy
  device_description:  M5Stack Bluetooth Proxy for Home Assistant

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: yoziru.esphome-m5-btproxy
    version: "2024.8.0"

packages:
  board: !include board.yml
  common: !include common.yml
  project: !include project.yml

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_rrm: true
  enable_btm: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_hotspot_password

captive_portal:
improv_serial:
