name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: ./.github/workflows/publish-common.yml
    with:
      files: esphome-m5-btproxy-m5stack-atoms3.yml,esphome-m5-btproxy-m5stack-nanoc6.yml
      name: ESPHome M5 BTProxy
